### ISSUE TITLE
Sales rep contact info Copy Text To Clipboard should have visible hint

### ISSUE THREAD

**Issue by ikathegreat** [derekantrican/SalesMap#14]
###### Requested Feature: After selecting a region or rep, you are able to copy the Sales rep's contact info to the clipboard by clicking the label containing the information. There's a "COPIED!" message afterwards.

Without experimenting by clicking things, the user has no way to know that said feature exists. Visual feedback could indicate that by clicking that text, something will happen.

The suggestion is altering the text color on mouse over, or separating that copy function into a separate button.

**Comment by derekantrican** [comment]
This has been fixed and will be incorporated into the next release (tool tip says "Click to Copy")
