### ISSUE TITLE
Split Sales rep contact info into additional functions

### ISSUE THREAD

**Issue by ikathegreat** [derekantrican/SalesMap#15]
###### Requested Feature: Currently the sales rep contact info is merged into one text label. By splitting it, I would like to click the sales rep's email to generate a new email to the sales rep. Which is different than the customer oriented email. There does not need to be any automatically generated text for this.

Also this would allow me to copy either the email, phone number, or both for the selected sales rep.

**Comment by derekantrican** [comment]
"labelContactResult" and "labelContactResult2" need to be split into 2 individual labels each

**Comment by derekantrican** [comment]
This should now be fixed and will be incorporated into the next release (tool tip says "Click to Copy")

_If there are found to be any problems with this, let me know_
