### ISSUE TITLE
RSM Email is Included in Off SMR Canned Email

### ISSUE THREAD

**Issue by coltlking** [derekantrican/SalesMap#18]
# For bugs:
###### Repro Steps: Select a state/region, then click the Off SMR email button.  The RSM email address is included in the body of the email.

![image](https://cloud.githubusercontent.com/assets/18350387/14386273/135bef22-fd72-11e5-9ce1-1363ae2cd6ca.png)

**Comment by derekantrican** [comment]
This has been fixed and will be incorporated into the next release
