### ISSUE TITLE
Change Off SMR Email Address to Support@sigmanest.com

### ISSUE THREAD

**Issue by coltlking** [derekantrican/SalesMap#19]
# For bugs:

**Comment by derekantrican** [comment]
This is not something that can be changed in the SalesMap program. The SalesMap program simply generates a `mailto:` link and uses your default mail client (and that mail client's default email address) to send the email.

To set the default email address in Outlook, please see this link: http://in5stepstutorials.com/ms-outlook/change-default-email-account-send-from-in-outlook.php
