### ISSUE TITLE
Sales Admin Updates

### ISSUE THREAD

**Issue by coltlking** [derekantrican/SalesMap#37]
Can Kat Ernest please be removed as a sales admin and Natalie Bookbinder be added?  Can sales admin territories be updated as well please?  If Megan Diefenbacher is responsible for any territories, can she be added also?  Thanks in advance!

**Comment by derekantrican** [comment]
I have replaced Kat with Natalie. Megan has not been added as she has the same responsibilities as Natalie and Natalie is training to take over her responsibilities. So the policy is: contact Natalie and if need be she'll ask Megan for help

You should see the changes if you restart SalesMap
