### ISSUE TITLE
Update Sales Admins for Territories

### ISSUE THREAD

**Issue by coltlking** [derekantrican/SalesMap#39]
For bugs:
=========

**Expected Behavior:** I'd like to know which SIM admin is responsible for which states.  

**Actual Behavior:**  Selecting some states still shows a SIM admin who no longer works at SigmaTEK. Unsurprising considering the SIM admins change faster than the weather around here 🤷‍♂️

**Repro Steps:**  Open SalesMap and select Ohio.  Manisha will still be listed as the SIM admin.

**Comment by derekantrican** [comment]
Ok, should be fixed if you restart SalesMap. Please let me know if it is not
