### ISSUE TITLE
Salesmen photo displayed simultaneously with region when region selected

### ISSUE THREAD

**Issue by dcape14** [derekantrican/SalesMap#8]
Add the photo of the salesperson to the image of the map so you can see who is associated with each state.
![derek](https://cloud.githubusercontent.com/assets/17727927/13608569/6c99a172-e523-11e5-94af-3087ca959a42.png)

**Comment by derekantrican** [comment]
The immediate problem posed by this screenshot (which may not be the final layout) is that if there are two reps, not only will two pictures have to be displayed, but also the picture shown above will be on top of (or behind) the contact information for the second rep.

Therefore, this may (at least in the early version) only be displayed for regions with one rep

**Comment by derekantrican** [comment]
Ideally, any feature that is implemented should be implemented across-the-board (a feature for one case should work for all similar cases). Therefore, because this is a problem with regions with multiple sales reps, I have decided not to implement this. (This can be readdressed at a later time)
